### ISSUE TITLE
반응형 작업 시에 큰 화면에서는 한 섹션이었던 것을 작은 화면에서는 2,3개의 섹션으로 쪼개고 싶은 경우, 방법이 있나요?

### ISSUE THREAD

**Issue by comme-modee** [flamecommit/react-datepicker#1]
작업환경은 리액트입니다.

모바일환경(window.innerWidth <= 700)에서는 섹션 갯수가 12개인 fullpageConatiner를,
PC환경(window.innerWidth > 700)에서는 섹션 갯수가 6개인 fullpageContainer가 랜더링되게 삼항연산자를 이용해 코딩했습니다.

이 경우에 맨 처음 접속했을때 랜더링된 컨테이너의 섹션 갯수가 만약 6개라면, 반응형으로 화면을 줄였을때 섹션이 12개로 재랜더링되어도(새로고침되는것은 아닙니다.) 기존의 섹션 갯수인 6개의 영향만을 받아 6개 이후로는 스크롤이 되지 않습니다.

마찬가지로 12개인 섹션에서 접속이 되면 반응형으로 화면을 늘여 6개의 섹션으로 재랜더링되어도 기존 섹션갯수대로 스크롤이 움직여 마치 에러가 발생한 듯 느껴집니다. 

결론:
반응형 작업 시에 큰 화면에서는 한 섹션이었던 것을 작은 화면에서는 2,3개의 섹션으로 쪼개고 싶은 경우, 방법이 있나요?

**Comment by flamecommit** [comment]
react-datepicker에 대한 문의가 맞나요?

**Comment by comme-modee** [comment]
죄송합니다. 페이지를 혼동했습니다. fullpage 라이브러리에 대한 문의였습니다!
